version: "3.7"

services:
  backend:
    image: backend-nodejs
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - /home/ubuntu/docker-volume/ssl2:/var/www/html
      - /home/ubuntu/backlog:/usr/app/logs
    container_name: "backend"
    hostname: "backend"
    expose:
      - 8081
networks:
  default:
    name: ubuntu_default
    external: true
